version: "3.0"
services:
  postgres96:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin@123
      POSTGRES_USER: postgres

  api:
    image: acelerex-api
    depends_on: ["postgres96"]
    ports:
    - 3030:3030


